// src/lib/blueprint/editor/view/node/index.tsx
import './index.scss'
import { UniNode } from '../../tool/uniNode'
import { Schemes, StarmapDataType } from '../../define'
import { RenderEmit, Presets } from 'rete-react-plugin'
// import { Tooltip } from 'antd'
import { getNodeTheme, computeBlockHeight } from '../../defaultTheme'
import { Control } from 'rete/_types/presets/classic'

const { RefSocket, RefControl } = Presets.classic
const MySocket = RefSocket<Schemes>
const MyControl = RefControl<Schemes>

type Props = {
  data: UniNode
  emit: RenderEmit<Schemes>
}

export function NodeView(props: Props) {
  const selected = props.data.selected || false
  const { id, label, width, height, category, inputs, outputs, controls } = props.data
  const { theme, style } = getNodeTheme(props.data.theme)
  // console.log(props)

  return <div
    className={`customized-node ${selected ? 'selected' : ''}`}
    style={{
      width: `${width}px`,
      height: `${height}px`,
      borderRadius: style.main.borderRadius
    }}
    data-testid="node"
  >
    <div
      className="border"
      style={{
        width: `${width}px`,
        height: `${height}px`,
        borderRadius: style.main.borderRadius,
        border: selected ? style.selected.border : style.main.border,
        filter: selected ? `drop-shadow(${style.selected.dropShadow})` : ''
      }}
    />
    {/* <Tooltip title={`${label}`} color={'#35bfff'}>
    </Tooltip> */}
    <div
      className="customized-title"
      style={{
        backgroundColor: theme.title,
        borderRadius: `${style.main.borderRadius} ${style.main.borderRadius} 0 0`,
        lineHeight: style.title.height,
        ...style.title
      }}
    >{ label }</div>
    <div
      className="customized-content"
      style={{
        backgroundColor: theme.content,
        height: `${height - parseFloat(style.title.height)}px`,
        borderRadius: `0 0 ${style.main.borderRadius} ${style.main.borderRadius}`
      }}
    >
      {
        category.map((cate, ci) => {
          return (
            <div
              className={`content-block align-${cate.align}`}
              style={{
                borderColor: theme.cateBorder,
                padding: `
                  ${cate.label || (category[ci - 1] &&!category[ci - 1].label) ? '0' : style.category.paddingVeritical} 
                  ${cate.align === 'left' ? '0' : style.category.paddingHorizontal} 
                  ${category[ci + 1] && !category[ci + 1].label ? '0' : style.category.paddingVeritical} 
                  ${cate.align === 'left' ? style.category.paddingHorizontal : '0'}
                `,
                borderBottom: (ci !== category.length - 1 && cate.label) ?style.category.borderBottomNotLast : '',
                '--socket-offset': style.category.socketOffset,
                marginBottom: cate.halfline ? `-${(computeBlockHeight(cate))}px` : 0
              } as React.CSSProperties}
              key={`cate_${ci}`}
            >
              {
                (cate.label ? <div
                  className="content-block-title"
                  style={{
                    lineHeight: style.blockTitle.height,
                    ...style.blockTitle
                  }}
                >{ cate.label }</div> : '')
              }
              {
                cate.content.map((item, ii) => {
                  const port = item.type === 'input' ? inputs[item.name] : outputs[item.name]
                  if (port) {
                    if ('dataType' in item) port.socket.dataType = item.dataType || StarmapDataType.UNKNOW
                    if ('flowType' in item) port.socket.flowType = item.flowType
                  }
                  // console.log(item, item.type === 'output', outputs[item.name])
                  return <div
                    className="content-socket-line"
                    key={`content_${ci}_${ii}`}
                    style={{
                      lineHeight: style.blockLine.height,
                      ...style.blockLine
                    }}
                  >
                    { item.label }
                    <div
                      className="socket-container"
                      style={{
                        '--socket-size': style.socket.size,
                        top: style.socket.top
                      } as React.CSSProperties}
                    >
                      {
                        item.type === 'control' ?
                          <MyControl
                            key={item.name}
                            name="control"
                            emit={props.emit}
                            payload={controls[item.name]}
                          />
                        : (
                          <>
                            {/* {`${item.type}_${item.name}_${item.dataType}`} */}
                            <MySocket
                              name={`${item.type}-socket`}
                              side={item.type}
                              emit={props.emit}
                              socketKey={item.name}
                              nodeId={id || ''}
                              payload={(item.type === 'input' ? inputs[item.name]!.socket : outputs[item.name]!.socket)}
                              data-testid={`${item.type}-socket`}
                            />
                          </>
                        )
                      }
                    </div>
                    {
                      item.type === 'input' && inputs[item.name]?.control && inputs[item.name]?.showControl ? (
                        <MyControl
                          key={item.name}
                          name="input-control"
                          emit={props.emit}
                          payload={inputs[item.name]!.control as Control}
                        />
                      ) : ''
                    }
                    {
                      item.type === 'output' && outputs[item.name]?.control && outputs[item.name]?.showControl ? (
                        <MyControl
                          key={item.name}
                          name="output-control"
                          emit={props.emit}
                          payload={outputs[item.name]!.control as Control}
                        />
                      ) : ''
                    }
                  </div>
                })
              }
            </div>
          )
        })
      }
    </div>
  </div>
}

// src/examples/rete/customization/dasv/view/node.vue
<template>
  <div
    class="customized-node"
    :class="{ selected: data.selected }"
    :style="{
      width: `${data.width}px`,
      height: `${data.height}px`
    }"
    data-testid="node"
  >
    <div class="border" />
    <div class="customized-title">{{ data.label }}</div>
    <div class="customized-content">
      <div class="content-block align-right">
        <div class="content-block-title">事件</div>
        <div class="content--socket-line"
          v-for="(v, k) in data.outputs"
          :key="`${k + seed}`"
        >
          {{ v.label }}
          <div class="socket-container">
            <Ref
              class="output-socket"
              :emit="emit"
              :data="{ type: 'socket', side: 'output', key: k, nodeId: data.id, payload: v.socket }"
              data-testid="output-socket"
            />
          </div>
        </div>
      </div>
      <!-- <Ref class="control" v-for="[key, control] in controls()" :key="key + seed" :emit="emit"
      :data="{ type: 'control', payload: control }" :data-testid="'control-' + key" /> -->
      <div class="content-block align-left no-next">
        <div class="content-block-title">动作</div>
        <div class="content--socket-line"
          v-for="(v, k) in data.inputs"
          :key="`${k + seed}`"
        >
          {{ v.label }}
          <div class="socket-container">
            <Ref
              class="input-socket"
              :emit="emit"
              :data="{ type: 'socket', side: 'input', key: k, nodeId: data.id, payload: v.socket }"
              data-testid="input-socket"
            />
          </div>
          <Ref
            class="input-control"
            v-show="v.control && v.showControl"
            :emit="emit"
            :data="{ type: 'control', payload: v.control }"
            data-testid="input-control"
          />
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import { Ref } from 'rete-vue-plugin'

function sortByIndex(entries:any) {
  entries.sort((a:any, b:any) => {
    const ai = a[1] && a[1].index || 0
    const bi = b[1] && b[1].index || 0

    return ai - bi
  })
  return entries
}

// 这个自定义组件的width和height目前是错误的（视图层和数据层是不一致的）
export default defineComponent({
  name: 'ReteBasic',
  props: ['data', 'emit', 'seed'],
  components: {
    Ref
  },
  methods: {
    // nodeStyles() {
    //   return {
    //     width: Number.isFinite(this.data.width) ? `${this.data.width}px` : '',
    //     height: Number.isFinite(this.data.height) ? `${this.data.height}px` : ''
    //   }
    // },
    inputs() {
      return sortByIndex(Object.entries(this.data.inputs))
    },
    controls() {
      return sortByIndex(Object.entries(this.data.controls))
    },
    outputs() {
      return sortByIndex(Object.entries(this.data.outputs))
    }
  },
  setup(props) {
    console.log(props.data, props.emit, props.seed)
  }
})
</script>

<style lang="scss">
  .customized-node{
    border-radius: 4px;
    box-sizing: border-box;
    position: relative;
    * {
      user-select: none;
    }
    &.selected {
      .border {
        border: 2px solid #0772ff;
        filter: drop-shadow(0px 0px 4px rgba(7, 114, 255, 0.4));
      }
    }
    .border {
      position: absolute;
      width: 100%;
      height: 100%;
      left: -2px;
      top: -2px;
      border-radius: 6px;
    }
    .customized-title{
      width: 100%;
      height: 32px;
      padding: 0 8px;
      box-sizing: border-box;
      background: #1A1A1A;
      border-radius: 4px 4px 0 0;
      text-overflow: ellipsis;
      overflow: hidden;
      white-space: nowrap;
      line-height: 32px;
      font-size: 14px;
      color: #fff;
      letter-spacing: 1px;
    }
    .customized-content{
      width: 100%;
      box-sizing: border-box;
      border-radius: 0 0 4px 4px;
      background: #232323;
      .content-block{
        padding-bottom: 8px;
        border-bottom: 1px solid #333333;
        &.align-right {
          text-align: right;
          padding-right: 8px;
          .content--socket-line{
            .socket-container {
              right: -13px; /* 8 + 5*/
            }
          }
        }
        &.align-left {
          text-align: left;
          padding-left: 8px;
          .content--socket-line{
            .socket-container {
              left: -13px; /* 8 + 5*/
            }
          }
        }
        &.no-next {
          border:none;
        }
        .content-block-title{
          height: 28px;
          line-height: 28px;
          font-size: 12px;
          letter-spacing: 1px;
          color: #666;
        }
        .content--socket-line{
          position: relative;
          height: 24px;
          line-height: 24px;
          font-size: 12px;
          letter-spacing: 2px;
          color: #efefef;
          .socket-container {
            position: absolute;
            border-radius: 50%;
            top: 7px; /* 24 / 2 - 5 */
          }
        }
      }
    }
  }
</style>
